version: '2'

services:


  db1:
    image: hauptmedia/mariadb:10.1
    hostname: db1
    container_name: db1
    ports:
      - 13306:3306
#    volumes:
#      - ./mysql/node1:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - REPLICATION_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - GALERA=On
      - NODE_NAME=db1
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://
    command: --wsrep-new-cluster
    networks:
      mariadb:
        ipv4_address: 172.43.43.10


  db2:
    image: hauptmedia/mariadb:10.1
    hostname: db2
    container_name: db2
    links:
      - db1
    ports:
      - 23306:3306
#    volumes:
#      - ./mysql/node2:/var/lib/mysql
    restart: always
    environment:
      - REPLICATION_PASSWORD=wordpress
      - GALERA=On
      - NODE_NAME=db2
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://db1
      - MYSQL_ROOT_PASSWORD=123
    networks:
      mariadb:
        ipv4_address: 172.43.43.11


  db3:
    image: hauptmedia/mariadb:10.1
    hostname: db3
    container_name: db3
    links:
      - db1
    ports:
      - 33306:3306
#    volumes:
#      - ./mysql/node3:/var/lib/mysql
    restart: always
    environment:
      - REPLICATION_PASSWORD=wordpress
      - GALERA=On
      - NODE_NAME=db3
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://db1
      - MYSQL_ROOT_PASSWORD=123
    networks:
      mariadb:
        ipv4_address: 172.43.43.12


  adm1:
    image: phpmyadmin/phpmyadmin
    container_name: adm1
    networks:
      mariadb:
        ipv4_address: 172.43.43.13
    links:
      - db1:mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123
      PMA_HOST: db1


  adm2:
    image: phpmyadmin/phpmyadmin
    container_name: adm2
    networks:
      mariadb:
        ipv4_address: 172.43.43.14
    links:
      - db2:mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123
      PMA_HOST: db2


  adm3:
    image: phpmyadmin/phpmyadmin
    container_name: adm3
    networks:
      mariadb:
        ipv4_address: 172.43.43.15
    links:
      - db3:mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123
      PMA_HOST: db3


  web1:
    image: wordpress
    container_name: web1
    networks:
      mariadb:
        ipv4_address: 172.43.43.16
    depends_on:
      - db1
    links:
      - db1:mysql
    restart: always
#    volumes:
#      - ./wordpress
    environment:
      WORDPRESS_DB_DATABASE: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db1:3306


  web2:
    image: wordpress
    container_name: web2
    networks:
      mariadb:
        ipv4_address: 172.43.43.17
    depends_on:
      - db2
    links:
      - db2:mysql
    restart: always
#    volumes:
#      - ./wordpress
    environment:
      WORDPRESS_DB_DATABASE: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db2:3306


  web3:
    image: wordpress
    container_name: web3
    networks:
      mariadb:
        ipv4_address: 172.43.43.18
    depends_on:
      - db3
    links:
      - db3:mysql
    restart: always
#    volumes:
#      - ./wordpress
    environment:
      WORDPRESS_DB_DATABASE: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db3:3306


  proxy:
    image: eeacms/haproxy
    container_name: haproxy
    depends_on:
      - web1
      - web2
      - web3
    environment:
      FRONTEND_NAME: web1
      FRONTEND_PORT: 80
      BACKENDS: "172.43.43.16 172.43.43.17 172.43.43.18"
      DNS_ENABLED: "true"
    networks:
      mariadb:
        ipv4_address: 172.43.43.7


networks:
  mariadb:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.43.43.0/24
          gateway: 172.43.43.1


